name: SchmidtNumber
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pip=23.3.2
  - pip:
    - cvxpy==1.5.3
    - jax==0.4.23
    - jaxlib==0.4.23
    - jupyterlab
    - matplotlib==3.8.0
    - numpy
    - platformdirs==4.1.0
    - qutip==5.0.0
    - qutip-qip==0.3.2
    - scipy==1.11.4
    - tqdm==4.66.1
    - optax==0.1.8
    - tensorflow==2.15.0
    - tensorflow-addons==0.23.0
    - ipywidgets
